import type { CanonicalSeedScenario } from "./types";

export const hostedPartialCoverageScenario: CanonicalSeedScenario = {
  scenarioId: "SCN_HOSTED_PARTIAL_COVERAGE",
  title: "Partial Hosted Coverage Awaiting Application",
  purpose:
    "Show a hosted check where deposit is already applied, hosted credit is available, and a guest-paid remainder still exists.",
  restaurantSlug: "olive-room-events",
  booking: {
    bookingRef: "BK-ORE-20260330-202",
    bookingType: "hosted_event",
    bookingName: "Northpeak Executive Dinner",
    status: "confirmed",
    organizerGuestRef: "rachel-morgan",
    payerGuestRef: "jonathan-reed",
    reservationGuestRef: "rachel-morgan",
    depositAmountCents: 50000,
    hostedAmountCents: 60000,
    partySize: 10,
    eventDate: "2026-03-30T20:00:00-04:00",
    notes: "Deposit already applied; hosted credit still needs operator application.",
  },
  deposit: {
    depositRef: "dep_ore_202",
    depositType: "event_deposit",
    state: "fully_applied",
    amountCents: 50000,
    appliedAmountCents: 50000,
    refundableAmountCents: 0,
    fundingOwnerGuestRef: "jonathan-reed",
    captureRef: "cap_dep_ore_202",
  },
  check: {
    externalCheckRef: "CHK-ORE-20260330-022",
    tableLabel: "PRIVATE-2",
    serviceChannel: "hosted_event",
    partySize: 10,
    subtotalAmountCents: 128000,
    taxAmountCents: 11360,
    tipAmountCents: 24000,
    totalAmountCents: 163360,
    openedAt: "2026-03-30T21:15:00-04:00",
  },
  primaryGuestKey: "jonathan-reed",
  payerGuestKey: "jonathan-reed",
  reservationGuestKey: "rachel-morgan",
  fragments: [
    {
      sourceSystem: "identity_service",
      externalIdentityRef: "booking_northpeak_202",
      rawName: "Rachel Morgan",
      rawEmail: "rachel.morgan@brighttable.com",
      guestKey: "rachel-morgan",
      metadata: {
        roleHint: "reservation",
      },
    },
    {
      sourceSystem: "terminal",
      externalIdentityRef: "hosted_payer_202",
      rawName: "Jonathan Reed",
      paymentAlias: "card_1881",
      guestKey: "jonathan-reed",
      metadata: {
        roleHint: "payer",
      },
    },
  ],
  events: [
    { type: "check_created", occurredAt: "2026-03-30T21:15:00-04:00" },
    {
      type: "booking_attached",
      occurredAt: "2026-03-30T21:15:10-04:00",
      payload: { bookingRef: "BK-ORE-20260330-202" },
    },
    {
      type: "organizer_attached",
      occurredAt: "2026-03-30T21:15:15-04:00",
      payload: { bookingRef: "BK-ORE-20260330-202" },
    },
    {
      type: "reservation_holder_attached",
      occurredAt: "2026-03-30T21:15:20-04:00",
      payload: { bookingRef: "BK-ORE-20260330-202" },
    },
    {
      type: "payer_attached",
      occurredAt: "2026-03-30T21:15:25-04:00",
      payload: { bookingRef: "BK-ORE-20260330-202" },
    },
    {
      type: "deposit_requested",
      occurredAt: "2026-03-29T10:00:00-04:00",
      payload: {
        depositRef: "dep_ore_202",
        depositType: "event_deposit",
        amountCents: 50000,
      },
    },
    {
      type: "deposit_captured",
      occurredAt: "2026-03-29T10:05:00-04:00",
      payload: {
        depositRef: "dep_ore_202",
        depositType: "event_deposit",
        amountCents: 50000,
        captureRef: "cap_dep_ore_202",
      },
    },
    {
      type: "deposit_applied_to_check",
      occurredAt: "2026-03-30T21:16:00-04:00",
      payload: {
        bookingRef: "BK-ORE-20260330-202",
        depositRef: "dep_ore_202",
        amountCents: 50000,
        reason: "Seeded deposit application before hosted coverage",
      },
    },
    { type: "check_opened", occurredAt: "2026-03-30T21:17:00-04:00" },
    { type: "items_synced", occurredAt: "2026-03-30T22:36:00-04:00" },
    {
      type: "payment_authorization_requested",
      occurredAt: "2026-03-30T22:40:00-04:00",
    },
    { type: "payment_authorized", occurredAt: "2026-03-30T22:40:05-04:00" },
    { type: "final_receipt_received", occurredAt: "2026-03-30T22:43:00-04:00" },
  ],
  expected: {
    paymentState: "authorized",
    receiptState: "received",
    rewardsState: "not_eligible",
    identityState: "linked_confident",
    bookingState: "attached",
    depositState: "fully_applied",
    hostedSettlementState: "hosted_pending",
    roleResolutionState: "resolved_with_split",
    depositAmountCents: 50000,
    depositAppliedAmountCents: 50000,
    hostedAmountCents: 60000,
    hostedAppliedAmountCents: 0,
    remainingBalanceCents: 113360,
    directPaymentDueCents: 113360,
    exceptionState: "action_required",
    serviceState: "awaiting_staff_action",
    exceptions: ["hosted_credit_available_not_applied"],
    nextActionOwner: "manager",
    nextActionText:
      "Apply hosted coverage to the check before confirming the remaining guest-paid balance.",
  },
};
